### ISSUE TITLE
Kd meu bichinho?

### ISSUE THREAD

**Issue by Nic-Lemes** [teteusAraujo/KdMeuBichinho#1]
Cara, pelo que vi parece sensacional...
Oq acha de colocar umas imagens no readme.md ou até mesmo hospedar o site no Gihub pages ou numa vercel da vida para podermos ver e usufruir do resultado final? Essa é minha sugestão.  ^U^

**Comment by teteusAraujo** [comment]
Valeu Nicolas... Essa é minha ideia , vou fazer o Readme.md em breve e depois o back end com Java e fazer o deploy no Heroku

**Comment by Nic-Lemes** [comment]
Entendi. Parece que vai ficar bel legal! Boa sorte!
